---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: instavote-deploy
  namespace: instavote
spec:
  secretRef:
    name: github-instavote
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/solomon-n/instavote-deploy
