apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: error-rate
  namespace: flux-system
spec:
  provider:
    type: prometheus
    address: http://flagger-prometheus:9090
  query: |
    100 - sum(
      rate(
        nginx_ingress_controller_requests{
          exported_namespace="{{ namespace }}",
          ingress="{{ ingress }}",
          status!~"5.*"
        }[{{ interval }}]
      )
    ) 
    / 
    sum(
      rate(
        nginx_ingress_controller_requests{
          exported_namespace="{{ namespace }}",
          ingress="{{ ingress }}"
        }[{{ interval }}]
      )
    ) 
    * 100